Feature/api
m4thod0x/TaskManager pull request #13
Opened 2021-12-12 16:20 UTC by m4thod0x

2021-12-12 16:55 UTC, greybutton requested changes

2021-12-12 16:55 UTC, greybutton commented on app/models/task.rb
> +  validates :author_id, presence: true
почему поменял?

2021-12-12 20:35 UTC, m4thod0x commented on app/models/task.rb
> +  validates :author_id, presence: true
Поменял, когда искал почему падал тест, выдавая ошибку валидации. Подумал, что раз в фабрике у Task поле author_id, то может его в валидации модели поменять? Потом, когда уже нашел причину падения теста task_test.rb, то о том изменении и не вспомнил. Тесты проходят и с :author и с :author_id.

2021-12-13 18:05 UTC, greybutton approved these changes

2021-12-13 19:31 UTC, merged