Feature/assignee
m4thod0x/TaskManager pull request #17
Opened 2022-02-10 11:54 UTC by m4thod0x

2022-02-14 17:52 UTC, greybutton requested changes
в app/javascript/components/TaskBoard/TaskBoard.js тоже презентер надо использовать

2022-02-14 17:52 UTC, greybutton commented on app/javascript/components/EditPopup/components/Form/Form.js
> +import UserSelect from "packs/components/UserSelect";
UserSelect from "components/UserSelect";

2022-02-14 17:52 UTC, greybutton commented on app/javascript/presenters/TaskPresenter.js
> +    expired_at: PropTypes.instanceOf(Date),
в жс camel case везде

2022-02-14 17:52 UTC, greybutton commented on app/controllers/api/v1/users_controller.rb
> +    users = User.ransack(ransack_params).result.page(page).per(1000)
почему 1000? per_page так же как page должен быть

2022-02-14 20:55 UTC, m4thod0x commented on app/controllers/api/v1/users_controller.rb
> +    users = User.ransack(ransack_params).result.page(page).per(1000)
Без него показывает по умолчанию только последних 10 пользователей.

2022-02-15 07:50 UTC, m4thod0x commented on app/controllers/api/v1/users_controller.rb
> +    users = User.ransack(ransack_params).result.page(page).per(1000)
> почему 1000? per_page так же как page должен быть

Без него показывает по умолчанию только последних 10 пользователей.

2022-02-15 13:56 UTC, greybutton approved these changes

2022-02-15 13:56 UTC, greybutton commented on app/javascript/presenters/TaskPresenter.js
> +    transitions: PropTypes.arrayOf(object),
можно просто PropTypes.array

2022-02-15 13:56 UTC, greybutton commented on app/javascript/presenters/TaskPresenter.js
> +import PropTypes, { object, string } from "prop-types";
`, { object, string }` убрать можно

2022-02-15 13:56 UTC, greybutton commented on app/controllers/api/v1/users_controller.rb
> +    users = User.ransack(ransack_params).result.page(page).per(1000)
это ок, фронт сам разберется сколько ему запросить

2022-02-15 15:28 UTC, merged